# -*- coding: utf-8 -*-
"""Readme.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ao5qySacAZFlqX4aIME_H-BnDhfplk-m
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md