# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141x9ThsJQ4Rmquw9oQu31JqkFWm1QqsD
"""

import http.server
import json
import os
import socketserver
from urllib.parse import urlparse

PORT = 8000
DATA_FILE = "tasks.txt"

tasks = []
next_id = 1


def save_tasks_to_file():
    """Сохраняет задачи в файл"""
    try:
        with open(DATA_FILE, 'w', encoding='utf-8') as f:
            data = {
                'tasks': tasks,
                'next_id': next_id
            }
            json.dump(data, f, ensure_ascii=False, indent=2)
    except Exception as e:
        print(f"Ошибка при сохранении в файл: {e}")


def load_tasks_from_file():
    """Загружает задачи из файла"""
    global tasks, next_id

    if os.path.exists(DATA_FILE):
        try:
            with open(DATA_FILE, 'r', encoding='utf-8') as f:
                data = json.load(f)
                tasks = data.get('tasks', [])
                next_id = data.get('next_id', 1)
                print(f"Загружено {len(tasks)} задач из файла")
        except Exception as e:
            print(f"Ошибка при загрузке из файла: {e}")
            tasks = []
            next_id = 1


class TaskHandler(http.server.SimpleHTTPRequestHandler):
    """Обработчик HTTP запросов для управления задачами"""

    def do_GET(self):
        """Обработка GET запросов"""
        parsed_path = urlparse(self.path)

        if parsed_path.path == "/tasks":
            self.handle_get_tasks()
        else:
            self.send_response(404)
            self.end_headers()

    def do_POST(self):
        """Обработка POST запросов"""
        parsed_path = urlparse(self.path)

        if parsed_path.path == "/tasks":
            self.handle_create_task()
        elif parsed_path.path.startswith("/tasks/") and parsed_path.path.endswith("/complete"):
            self.handle_complete_task()
        else:
            self.send_response(404)
            self.end_headers()

    def handle_get_tasks(self):
        """Возвращает список всех задач"""
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(tasks).encode())

    def handle_create_task(self):
        """Создание новой задачи"""
        global next_id

        content_length = int(self.headers.get('Content-Length', 0))
        post_data = self.rfile.read(content_length)

        try:
            task_data = json.loads(post_data.decode('utf-8'))

            if 'title' not in task_data or 'priority' not in task_data:
                self.send_response(400)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({"error": "Missing required fields"}).encode())
                return

            new_task = {
                'id': next_id,
                'title': task_data['title'],
                'priority': task_data['priority'],
                'isDone': False
            }

            tasks.append(new_task)
            next_id += 1

            save_tasks_to_file()

            self.send_response(201)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps(new_task).encode())

        except json.JSONDecodeError:
            self.send_response(400)
            self.send_header('Content-type', 'application/json')
            self.end_headers()
            self.wfile.write(json.dumps({"error": "Invalid JSON"}).encode())

    def handle_complete_task(self):
        """Отмечает задачу как выполненную"""
        path_parts = self.path.split('/')
        if len(path_parts) >= 3:
            try:
                task_id = int(path_parts[2])

                for task in tasks:
                    if task['id'] == task_id:
                        task['isDone'] = True
                        save_tasks_to_file()
                        self.send_response(200)
                        self.end_headers()
                        return

                self.send_response(404)
                self.end_headers()
            except ValueError:
                self.send_response(404)
                self.end_headers()
        else:
            self.send_response(404)
            self.end_headers()


def run_server():
    """Запускает HTTP сервер"""
    load_tasks_from_file()

    handler = TaskHandler
    socketserver.TCPServer.allow_reuse_address = True

    with socketserver.TCPServer(("", PORT), handler) as httpd:
        print(f"Сервер запущен на порту {PORT}")
        print(f"Доступные эндпоинты:")
        print(f"  GET  /tasks - получить все задачи")
        print(f"  POST /tasks - создать задачу")
        print(f"  POST /tasks/<id>/complete - отметить задачу как выполненную")
        print(f"Данные сохраняются в файл: {DATA_FILE}")
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nСервер остановлен")
            save_tasks_to_file()


if __name__ == "__main__":
    run_server()